api/contas/urls.py
from django.urls import path

from core.views import index

from contas.views import PagamentoCreate

app_name = 'contas'
urlpatterns = [
    path('pagamento/', PagamentoCreate.as_view()),
]

api/core/urls.py
from django.urls import path

from core.views import index

app_name = 'core'
urlpatterns = [
    path('', index, name='index'),
]

api/project_root/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from rest_framework_swagger.views import get_swagger_view

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('core.urls')),
                  path('contas/', include('contas.urls')),
                  url(r'^docs/$', get_swagger_view(title='Endpoints'), name='api_docs'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

api/contas/models.py
from django.db import models

# Create your models here.
from django.db.models import Model


class Pagamento(models.Model):
    nome = models.CharField('Nome', max_length=100)
    valor_original = models.FloatField('Valor')
    valor_corrigido = models.FloatField('Valor', null=True, blank=True)
    vencimento = models.DateField('Data de Vencimento', help_text='Utilize o formato YYYY-MM-DD')
    pagamento = models.DateField('Data de Pagamento', help_text='Utilize o formato YYYY-MM-DD')

    class Meta:
        verbose_name = 'Pagamento'
        verbose_name_plural = 'Contas'
        ordering = ['pagamento']

    def get_valor_corrigido(self):
        if self.pagamento <= self.vencimento:
            return self.valor_original
        else:
            diferenca_em_dias = (self.pagamento - self.vencimento).days
            if diferenca_em_dias <= 3:
                multa = self.valor_original * 0.02
                juros = self.valor_original * (diferenca_em_dias * 0.01)
            elif 3 < diferenca_em_dias <= 5:
                multa = self.valor_original * 0.03
                juros = self.valor_original * (diferenca_em_dias * 0.02)
            else:
                multa = self.valor_original * 0.05
                juros = self.valor_original * (diferenca_em_dias * 0.03)
            return self.valor_original + multa + juros

    def save(self, *args, **kwargs):
        self.valor_corrigido = self.get_valor_corrigido()
        super(Pagamento, self).save(*args, **kwargs)

    def __str__(self):
        return self.nome

api/core/models.py
from django.db import models

# Create your models here.

api/contas/views.py
from django.shortcuts import render

# Create your views here.
from rest_framework.generics import CreateAPIView
from rest_framework.parsers import FormParser

from contas.serializers import PagamentoSerializer
from rest_framework.permissions import AllowAny


class PagamentoCreate(CreateAPIView):
    """
        Cadastra um pagamento. Clique em Try Out para cadastrar por aqui.
    """
    serializer_class = PagamentoSerializer
    permission_classes = (AllowAny,)
    parser_classes = [FormParser]

api/core/views.py
from django.shortcuts import render, redirect

from contas.models import Pagamento


def index(request):
    pagamentos = Pagamento.objects.all()
    context = {
        'pagamentos': pagamentos
    }
    return render(request, 'core/index.html', context=context)

api/core/templates/core/base.html
<!DOCTYPE html>
<html lang="pt-br">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Teste técnico Django Rest Docker Postgres">
    <meta name="author" content="Cassiano Andrei Schneider">

    <title>{% block title %}Minhas contas{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/heroic-features.css' %}" rel="stylesheet">
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'core:index' %}"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'core:index' %}">Início
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container">

    {% if messages %}
        {% for message in messages %}
            <div style='text-align:center;'
                 class="alert alert-rounded alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}">
                <button type="button" class="close" data-dismiss="alert">x</button>
                <strong>{{ message|safe }}</strong>
            </div>
        {% endfor %}
    {% endif %}

    <!-- Page Features -->
    {% block content %}

    {% endblock %}
    <!-- /.row -->

</div>
<!-- /.container -->

<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Teste técnico 2021</p>
    </div>
    <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
{% block page_scripts %}{% endblock %}

</body>

</html>

api/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
    <!-- Jumbotron Header -->
    <header class="jumbotron my-4">
        <h1 class="display-3">Bem vindo!</h1>
        <p class="lead">Lista de contas, para cadastrar uma nova conta, utilize a API</p>
        <a target="_blank" href="{% url 'api_docs' %}" class="btn btn-primary btn-lg">API</a>
    </header>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"
          integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

    <br/>

    <div class="row text-center mt-2">
    <div class="col-lg-12 col-md-12 mb-12">
        <h4>Lista de pagamentos</h4>
        <table class="table">
            <thead>
            <th>Nome</th>
            <th>Valor Original</th>
            <th>Valor Corrigido</th>
            <th>Vencimento</th>
            <th>Pagamento</th>
            </thead>
            <tbody>
            {% for p in pagamentos %}
                <tr>
                    <td>{{ p.nome }}</td>
                    <td>R$ {{ p.valor_original }}</td>
                    <td>R$ {{ p.valor_corrigido }}</td>
                    <td>{{ p.vencimento }}</td>
                    <td>{{ p.pagamento }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block page_scripts %}

{% endblock %}